### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by hpoit** [google/pageloader#187] opened 2019-06-30 00:17 UTC
```
Working dir: /Users/xxx/WebstormProjects/toh-5-master
/usr/local/Cellar/dart/2.3.2/libexec/bin/pub get
Resolving dependencies...
Because pageloader >=3.0.0 depends on build_config ^0.3.1 and build_runner >=1.3.4 depends on build_config >=0.4.0 <0.4.1, pageloader >=3.0.0 is incompatible with build_runner >=1.3.4.
So, because angular_tour_of_heroes depends on both build_runner ^1.5.0 and pageloader ^3.0.0, version solving failed.
Process finished with exit code 1
```

**Comment by StorminGorman** [comment] 2019-07-02 20:25
I have a proposed fix commented on:
https://github.com/google/pageloader/issues/184#issuecomment-507831037

**Comment by mk13** [comment] 2019-08-07 16:30
Duplicate of #191

**Closed by mk13** 2019-08-07 16:30 UTC
